name: test

on:
  pull_request:
    types: [opened, edited]
    branches:
      - "main"
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"
      - run: npm install
      - run: npx tsc --noEmit # Checks TypeScript compilation
      - run: npm test # Runs Jest tests
